### PR TITLE
Simplify substratevm built

### PR DESCRIPTION
**Pull request by zakkak**
Tested with `mx build --projects SVM_HOSTED`
Note that this won't give you an `svm.jar` but an `svm-hosted.jar`, which I guess you can rename...

### CODE REVIEW

**Comment by galderz** [comment]
Thanks @zakkak, I'll try it out locally shortly.

**Comment by galderz** [comment]
@zakkak Tried it and it works, and it does seem to give you an `svm.jar`. This is located in `/tmp/mandrel/substratevm/mxbuild/dists/jdk11/svm.jar` when I run it locally inside the docker container.

I've double-checked and this jar has indeed the same contents as the normal `svm.jar`. And of course, no libffi is downloaded.

Bravo 👏👏👏

**Comment by galderz** [comment]
Oh one sec, that jar might be from another run (since volumes are use)

**Comment by zakkak** [comment]
Yes that's probably from a different run.
I think that's easy to check by inspecting the modification timestamps of the jars ;)

**Comment by galderz** [comment]
@zakkak I've pushed some changes to master to do an `mx clean` before the build to highlight errors introduced by changes like this.

So, jar name aside, there are some clear differences between the two jars (see [here](https://gist.github.com/galderz/236f47e7bf3faaced3b96b335d8e3ee8)). The files there are missing from `svm-hosted.jar` as opposed to `svm.jar`.

For this change to be acceptable, you should provide some proof that Quarkus works fine without these classes/files. Also, ideally we'll produce a single jar that works for the Maven dependency in Quarkus JVM mode, and for the native image generation in Quarkus Native mode. So, the verification should really apply to both. Have you already carried out such test? If not, could you look into it?

**Comment by zakkak** [comment]
Hmm unfortunately it doesn't work. The first issue I came across is a dependency on `com.oracle.svm.core.posix` which is not included in the `svm-hosted.jar`.

And I see that this package is only included in the SVM _mx project_ which brings the libffi as well :(

**Comment by galderz** [comment]
Pity. Thanks for giving it a go though @zakkak!

**Pull request closed without merging**
